const nomes = {
"0-1": "Sword Of Celestial [SS]",
"0-2": "Sword Of Calliuws [SS]",
"0-3": "Sword Classico V1 [BLACK]",
"0-4": "Sword Of Fable [R]",
"0-5": "Sword Of Dragon Fire [U.R]",
"0-6": "Sword Of Dragon Ice [U.R]",
"0-7": "Sword Of Golden Dragon [U.R]",
"0-8": "Sword Of Obscure [U.R]",
"0-9": "Dark Night Of Sword [LIMITED]",
"0-10": "Ancestral Of Sword [LIMITED]",
"0-11": "Old Storn Of Sword [Premium]",
"0-12": "Santa Of Sword [LIMITED]",
"0-13": "Sword Of Thanatos [R]",
"0-14": "Sword Of Imperial Dragon [R]",
"0-15": "Sword Of Cronus [R]",
"0-16": "Sword Of Hell mine [R]",
"0-17": "Sword Of Purple [U.R]",
"0-18": "Sword Of  IGriSS[R]",
"0-19": "Sword Of Flamerger [U.R]",
"0-20": "Sword Of Style Purple [MD]",
"0-21": "Sword Of War Purple [MD]",
"0-25": "Sword White Gold [SS]",
"0-24": "Sword Rei do BC [LIMITED]",
"0-23": "Sword Of Imperiom [R]",
"0-22": "Sword Of Lidiam [R]",       
"0-26": "Sword Maximus 06 V3 [BLACK]",       
};
